// <auto-generated />
namespace MRT.DataContexts.DataMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddStateCoverages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStateCoverages));
        
        string IMigrationMetadata.Id
        {
            get { return "201808042038125_AddStateCoverages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
