SET IDENTITY_INSERT [dbo].[States] ON
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (0, N'Alabama', N'AL')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (1, N'Alaska', N'AK')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (2, N'Arizona', N'AZ')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (3, N'Arkansas', N'AR')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (4, N'California', N'CA')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (5, N'Colorado', N'CO')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (6, N'Connecticut', N'CT')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (7, N'District of Columbia', N'DC')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (8, N'Delaware', N'DE')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (9, N'Florida', N'FL')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (10, N'Georgia', N'GA')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (11, N'Hawaii', N'HI')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (12, N'Idaho', N'ID')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (13, N'Illinois', N'IL')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (14, N'Indiana', N'IN')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (15, N'Iowa', N'IA')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (16, N'Kansas', N'KS')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (17, N'Kentucky', N'KY')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (18, N'Louisiana', N'LA')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (19, N'Maine', N'ME')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (20, N'Maryland', N'MD')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (21, N'Massachusetts', N'MA')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (22, N'Michigan', N'MI')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (23, N'Minnesota', N'MN')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (24, N'Mississippi', N'MS')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (25, N'Missouri', N'MO')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (26, N'Montana', N'MT')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (27, N'Nebraska', N'NE')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (28, N'Nevada', N'NV')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (29, N'New Hampshire', N'NH')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (30, N'New Jersey', N'NJ')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (31, N'New Mexico', N'NM')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (32, N'New York', N'NY')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (33, N'North Carolina', N'NC')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (34, N'North Dakota', N'ND')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (35, N'Ohio', N'OH')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (36, N'Oklahoma', N'OK')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (37, N'Oregon', N'OR')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (38, N'Pennsylvania', N'PA')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (39, N'Rhode Island', N'RI')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (40, N'South Carolina', N'SC')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (41, N'South Dakota', N'SD')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (42, N'Tennessee', N'TN')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (43, N'Texas', N'TX')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (44, N'Utah', N'UT')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (45, N'Vermont', N'VT')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (46, N'Virginia', N'VA')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (47, N'Washington', N'WA')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (48, N'West Virginia', N'WV')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (49, N'Wisconsin', N'WI')
INSERT INTO [dbo].[States] ([Id], [Name], [Abbreviation]) VALUES (50, N'Wyoming', N'WY')
SET IDENTITY_INSERT [dbo].[States] OFF
