SET IDENTITY_INSERT [dbo].[Codes] ON
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1, N'0005', N'Christmas Tree Farm & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (6, N'0008', N'Harvesting by Contract Using Hand Labor Exclusively & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (8, N'0016', N'Pecan Harvesting & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (9, N'0034', N'Hatchery—Poultry—Store Operations Only')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (10, N'0035', N'Aquatic Plants—Growing & Harvesting & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (16, N'0036', N'Farm—Dairy & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (17, N'0037', N'Anhydrous Ammonia Application—Agricultural—By Contract & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (23, N'0042', N'Hydro-Mulching & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (25, N'0050', N'Brush or Weed Control by Contractor—Chemical & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (28, N'0079', N'Farm—Berry or Vineyard & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (29, N'0083', N'Breeding Farm or Stable & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (38, N'0106', N'Transmission Line Clearing and/or Maintenance—Tree Trimming Along Existing Lines & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (40, N'0113', N'Alligator Farm & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (55, N'0170', N'Farm—Animal Raising & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (56, N'0251', N'Irrigation Works Operation & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (57, N'0400', N'Cotton Compressing & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (58, N'0401', N'Cotton Gin—All Employees')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (59, N'0908', N'Domestic Workers—Residences—Part-Time')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (60, N'0913', N'Domestic Workers—Residences—Per Capita Basis')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (62, N'0917', N'Pet Sitting Services & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (64, N'0923', N'Domestic Workers—Residences—Payroll Basis')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (66, N'1005', N'Coal Mining—Surface & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (67, N'1164', N'Mining NOC—Not Coal—Underground & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (68, N'1165', N'Coal Mining & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (74, N'1320', N'Gas or Oil—Lease Operator—Natural Gas—All Operations & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (76, N'1321', N'Compressor Station Operation & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (82, N'1322', N'Oil or Gas—Well—Cleaning or Swabbing of Wells—By Specialist Contractor—No Drilling & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (83, N'1430', N'Lead Mfg. & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (85, N'1438', N'Blast Furnace Operation & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (92, N'1452', N'Graphite Mfg.—Not Artificial & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (94, N'1463', N'Asphalt Works & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (96, N'1472', N'Alcohol Mfg.—Wood & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (100, N'1624', N'Quarry NOC & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (104, N'1642', N'Lime Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (105, N'1654', N'Quarry—Cement Rock—Surface & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (106, N'1655', N'Quarry—Limestone—Surface & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (107, N'1699', N'Rock Wool Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (108, N'1701', N'Abrasive Wheel Mfg. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (124, N'1710', N'Stone Crushing & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (125, N'1741', N'Flint or Spar Grinding & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (128, N'1747', N'Clay Milling & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (131, N'1748', N'Abrasive Wheel Mfg. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (132, N'1803', N'Fiberglass Insulation Mfg. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (143, N'1852', N'Asbestos Goods Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (144, N'1853', N'Mica Goods Mfg. & Mica Preparing.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (145, N'1860', N'Abrasive Paper or Cloth Preparation')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (146, N'1924', N'Cable or Wire Rope Mfg.—Iron or Steel')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (149, N'1925', N'Die Casting Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (150, N'2002', N'Pasta or Noodle Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (151, N'2003', N'Bakery & Drivers, Route Supervisors')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (159, N'2014', N'Alfalfa Dehydrating and Processing')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (167, N'2016', N'Cereal or Bar Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (168, N'2021', N'Sugar Manufacturing or Refining From Sugar Cane or Sugar Beets')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (169, N'2032', N'Yarn or Thread Mfg.—Silk')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (170, N'2039', N'Ice-Cream Mfg. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (171, N'2040', N'Ice Cream Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (172, N'2041', N'Beet Sugar Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (182, N'2065', N'Condensed Milk Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (185, N'2068', N'Butter or Cheese Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (190, N'2070', N'Butter or Cheese Mfg. & Route Supervisors, Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (196, N'2081', N'Butchering')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (199, N'2089', N'Packing House—All Operations.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (200, N'2095', N'Beef Jerky Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (205, N'2105', N'Fruit Packing')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (207, N'2110', N'Pickle Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (208, N'2111', N'Cannery NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (212, N'2112', N'Fruit Evaporating or Preserving')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (213, N'2114', N'Crab Processing & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (217, N'2121', N'Brewery & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (218, N'2130', N'Alcohol Mfg.—Grain—All Operations')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (221, N'2131', N'Spirituous Liquor Bottling')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (222, N'2143', N'Fruit Juice Mfg. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (224, N'2157', N'Beverage Mfg. NOC & Route Supervisors, Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (231, N'2172', N'Cigar Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (234, N'2174', N'Tobacco—Rehandling or Warehousing')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (235, N'2211', N'Cotton Cleaning and/or Blending—No Gin Operations')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (237, N'2220', N'Cap Mfg.—Fabric')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (248, N'2260', N'Wool Combing or Scouring')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (249, N'2286', N'Wool Spinning and Weaving')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (251, N'2288', N'Felting Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (252, N'2300', N'Plush or Velvet Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (254, N'2302', N'Silk Thread or Yarn Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (257, N'2305', N'Rayon Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (259, N'2361', N'Hosiery Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (260, N'2362', N'Glove or Mitten Mfg.—Knit.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (263, N'2380', N'Camouflage Net Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (266, N'2386', N'Lace Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (267, N'2388', N'Embroidery Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (268, N'2402', N'Carpet or Rug Mfg. NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (270, N'2413', N'Textile Bleaching, Dyeing, Mercerizing, Finishing')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (271, N'2416', N'Thread or Yarn Dyeing or Finishing')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (273, N'2417', N'Cloth Printing.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (274, N'2501', N'Clothing Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (283, N'2503', N'Tailoring or Dressmaking—Custom Exclusively')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (284, N'2532', N'Millinery Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (285, N'2534', N'Hair Goods Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (288, N'2560', N'Parachute Mfg. and Servicing')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (290, N'2570', N'Box Spring or Mattress Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (292, N'2576', N'Awning or Tent Mfg.—Fabric—Shop')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (296, N'2578', N'Bag or Sack Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (299, N'2581', N'Carpet, Rug, or Upholstery Cleaning—Shop or Outside & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (304, N'2583', N'Cleaning or Dyeing & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (308, N'2585', N'Carpet, Rug, or Upholstery Cleaning—Shop or Outside & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (313, N'2586', N'Cleaning or Dyeing & Route Supervisors, Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (315, N'2587', N'Toilet or Towel Supply Co. and Route Supervisors & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (318, N'2589', N'Dry Cleaning and Laundry Store—Retail & Route Supervisors, Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (320, N'2600', N'Fur Processing—Preparing Skins')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (321, N'2623', N'Leather Mfg.—Including Tanning, Leather Embossing, and Wool Pulling')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (322, N'2651', N'Shoe Findings Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (324, N'2660', N'Boot or Shoe Mfg. NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (326, N'2670', N'Glove Mfg.—Leather or Textile.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (327, N'2683', N'Bag Mfg.—Cloth or Leather')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (334, N'2688', N'Boot or Shoe Mfg. NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (346, N'2701', N'Logging or Tree Removal—Log Hauling & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (347, N'2702', N'Brush or Timber Cutting and Removal & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (350, N'2705', N'Logging or Lumbering—Pulpwood Only & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (351, N'2709', N'Logging or Tree Removal—Mechanized Equipment Operators')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (352, N'2710', N'Log Debarking or Pole Peeling & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (354, N'2714', N'Veneer Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (355, N'2719', N'Logging or Lumbering—Mechanized Felling Machines (Includes the Use of Chain Saws for Delimbing & Bucking) & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (356, N'2731', N'Carpet Tack Strip Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (360, N'2735', N'Barrel Stock Mfg.—Wood.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (365, N'2759', N'Box Mfg.—Box Shook or Pallet—Wooden')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (367, N'2790', N'Pattern Making NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (368, N'2797', N'Manufactured, Modular, or Prefabricated Home Manufacturing—Shop Work—All Operations & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (369, N'2799', N'Manufactured, Modular, or Prefabricated Home Setup, Hookup, or Installation at Building Site')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (370, N'2802', N'Barrel Assembly & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (387, N'2835', N'Broom, Brush, or Mop Mfg. NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (390, N'2836', N'Brush or Broom Mfg. NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (391, N'2841', N'Brush or Broom Handle Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (400, N'2881', N'Billiard Table Mfg. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (439, N'2883', N'Furniture Manufacturing and Cabinet Shop—Wood—NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (440, N'2913', N'Rattan, Willow, or Twisted Fiber Products Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (443, N'2915', N'Plywood Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (445, N'2916', N'Veneer Products Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (446, N'2923', N'Musical Instrument Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (447, N'2942', N'Crayon, Pencil, or Penholder Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (450, N'2960', N'Pole, Post, or Tie Yard & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (453, N'3004', N'Iron or Steel Mfg.—All Types & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (455, N'3018', N'Iron or Steel—Manufacturing—Rolling Mill & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (456, N'3022', N'Copper Tubing Drawing & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (457, N'3027', N'Lead Works & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (460, N'3028', N'Pipe or Tube Mfg.—Iron, Steel, or Cast Iron & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (462, N'3030', N'Iron or Steel—Fabrication—Ironworks or Steelworks—Shop—Structural & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (463, N'3040', N'Building Mfg.—Portable—Metal—Shop & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (478, N'3041', N'Iron or Steel—Fabrication—Iron Works—Shop—Decorative or Artistic and Foundries, Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (480, N'3042', N'Elevator or Escalator Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (482, N'3064', N'Sign Manufacturing—Metal')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (487, N'3066', N'Aircraft Subassemblies Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (536, N'3076', N'Airplane Subassemblies Mfg.—Metal')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (543, N'3081', N'Enameled Ironware Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (545, N'3082', N'Wheel Mfg.—Railroad Car')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (546, N'3085', N'Aluminum Foundry—Cast Form Process')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (550, N'3110', N'Chain Mfg.—Forged')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (553, N'3111', N'Pipe Bending and Cutting')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (557, N'3113', N'Cutlery Mfg. NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (564, N'3114', N'Automatic Screw Machine Products Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (569, N'3118', N'File Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (572, N'3119', N'Needle Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (574, N'3122', N'Cutlery Mfg. NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (576, N'3126', N'Automatic Sprinkler Head Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (597, N'3131', N'Button or Fastener Mfg.—Metal')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (600, N'3132', N'Anchor Bolt Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (606, N'3145', N'Automatic Screw Machine Products Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (608, N'3146', N'Anchor Tie-Down Mfg. for Mobile Homes')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (628, N'3169', N'Stove Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (629, N'3175', N'Heater or Radiator Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (631, N'3179', N'Air Conditioner Mfg.—Refrigerated—Auto and Window Type')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (647, N'3180', N'Electric or Gas Lighting Fixtures Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (649, N'3188', N'Plumbers’ Supplies Mfg. NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (650, N'3220', N'Can Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (654, N'3223', N'Lamp Mfg. & Repair')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (657, N'3224', N'Agate or Enamel Ware Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (659, N'3227', N'Aluminum Extrusion Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (662, N'3240', N'Cable or Wire Rope Mfg.—Iron or Steel.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (664, N'3241', N'Wire Drawing—Iron or Steel')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (665, N'3255', N'Wire Cloth Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (666, N'3257', N'Air Conditioner Filter Mfg.—Metal')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (676, N'3270', N'Eyelet Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (681, N'3300', N'Bed Spring or Wire Mattress Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (683, N'3303', N'Spring Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (684, N'3307', N'Heat Treating—Metal.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (685, N'3315', N'Brass or Copper Goods Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (688, N'3316', N'Explosives or Ammunition—Cartridge or Shell Case Mfg.—Metal')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (689, N'3331', N'Lead Mfg. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (695, N'3334', N'Tinfoil Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (696, N'3336', N'Castings Mfg.—Metal—Lost Wax Process')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (698, N'3365', N'Hard Banding Service—Field & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (705, N'3372', N'Anodizing')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (712, N'3373', N'Galvanizing or Tinning—Not Electrolytic.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (714, N'3383', N'Belt Buckle Mfg.—Brass, Silver, Etc.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (719, N'3385', N'Clock Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (721, N'3400', N'Automobile—Stamped Parts Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (725, N'3507', N'Agricultural Machinery Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (744, N'3515', N'Loom Harness or Reed Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (747, N'3548', N'Arms Mfg. NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (750, N'3559', N'Confection Machine Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (752, N'3574', N'Adding, Computing, Recording, or Office Machine Mfg. NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (758, N'3581', N'Fuel Injection Device Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (759, N'3612', N'Engine Mfg. NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (761, N'3620', N'Heat Exchanger Cleaning in Shop')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (765, N'3629', N'Arms Mfg.—Small')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (774, N'3632', N'Drill Bit Repair—Rock')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (784, N'3634', N'Automatic Sprinkler Head Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (788, N'3635', N'Gear Mfg. or Grinding.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (789, N'3638', N'Ball or Roller Bearing Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (791, N'3639', N'Explosives or Ammunition—Projectile or Shell Mfg. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (792, N'3642', N'Battery Mfg.—Dry')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (793, N'3643', N'Boiler Control Panel Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (800, N'3647', N'Battery Mfg.—Storage')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (801, N'3648', N'Automobile Lighting, Ignition, or Starting Apparatus Mfg. NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (805, N'3681', N'Aircraft Radio Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (818, N'3685', N'Air Pressure or Steam Gauge Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (835, N'3719', N'Compressor Station Construction & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (840, N'3724', N'Air Conditioning Systems—Heating and/or Cooling—Not Portable—Installation of Air Conditioning Machinery & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (863, N'3726', N'Boiler Installation or Repair')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (865, N'3803', N'Automobile—Wheel Mfg.—Metal—Not Cast')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (866, N'3805', N'Aircraft Engine Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (872, N'3807', N'Automobile Radiator Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (874, N'3808', N'Automobile Mfg. or Assembly')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (875, N'3821', N'Aircraft Dismantling for Usable Parts & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (877, N'3822', N'Ambulance Body Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (880, N'3823', N'Automobile, Bus, Truck, or Trailer Body Mfg.—Riveted or Welded')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (882, N'3824', N'Automobile, Bus, Truck, or Trailer Body Mfg.—NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (890, N'3826', N'Aircraft Engine Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (892, N'3827', N'Automobile—Engine Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (894, N'3830', N'Airplane Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (895, N'3851', N'Motorcycle Mfg. or Assembly')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (896, N'3865', N'Baby Carriage Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (898, N'3881', N'Car Mfg.—Railroad & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (900, N'4000', N'Blasting—Rock—Specialty Contractors & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (917, N'4021', N'Concrete Block Glazing & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (918, N'4024', N'Insulator Mfg.— Porcelain—For Electrical Wiring & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (920, N'4034', N'Burial Vault Mfg.—Concrete—Including Installation & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (926, N'4036', N'Chip Board Mfg. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (932, N'4038', N'Cast Stone Mfg.—Architectural')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (934, N'4045', N'Cement Pave Stone Mfg. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (936, N'4053', N'Pottery Mfg.—China or Tableware')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (938, N'4061', N'Pottery Mfg.—Earthenware—Glazed or Porcelain—Hand Molded or Cast')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (939, N'4062', N'China Mfg.—Decorative')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (944, N'4101', N'Cathedral or Art Glass Window Mfg. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (951, N'4109', N'Integrated Circuit Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (952, N'4110', N'Electric Bulb Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (954, N'4111', N'Glassware Mfg.—No Automatic Blowing Machines')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (955, N'4112', N'Flashlight Mfg. or Assembly')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (963, N'4113', N'Glass Mfg.—Cut')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (964, N'4114', N'Glassware Mfg. NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (965, N'4130', N'Glass—Insulated Window Fabrication')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (967, N'4131', N'Mirror Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (968, N'4133', N'Cathedral or Art Glass Window Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (970, N'4149', N'Optical Goods Mfg. NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (971, N'4150', N'Lens Mfg.—Ground')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (973, N'4206', N'Wood Chip Mills—Permanent Location—Processing Logs Into Pulp')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (974, N'4207', N'Pulp Mfg.—Chemical Process')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (975, N'4239', N'Paper Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (976, N'4240', N'Box Mfg.—Set-Up Paper')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (977, N'4243', N'Box Mfg.—Folding Paper—NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (980, N'4244', N'Box Mfg.—Corrugated')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (982, N'4250', N'Paper Coating')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (986, N'4251', N'Carbon Paper or Typewriter Ribbon Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (992, N'4263', N'Fiber Goods Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (993, N'4273', N'Bag Mfg.—Paper')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (994, N'4279', N'Bag Mfg.—From Glassine Material')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1005, N'4282', N'Boot or Shoe Pattern Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1008, N'4283', N'Asphalt Products Mfg. NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1013, N'4299', N'Addressing or Mailing Co. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1024, N'4304', N'Newspaper Publishing')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1026, N'4307', N'Bookbinding')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1027, N'4351', N'Advertising Agency—Includes Photography and Photo Engraving')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1032, N'4352', N'China Decorating—By Hand')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1034, N'4360', N'Motion Picture—Production—In Studios or Outside—All Operations—Includes the Development of Negatives & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1035, N'4361', N'Film Processing & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1040, N'4362', N'Film Exchange')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1042, N'4410', N'Carpet Padding Mfg.—Rubberized')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1043, N'4417', N'Boot or Shoe Mfg.—Rubber')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1045, N'4420', N'Rubber Tire Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1048, N'4431', N'Magnetic and Optical Recording Media Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1050, N'4432', N'Carbon Paper or Typewriter Ribbon Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1059, N'4439', N'Lacquer or Spirit Varnish Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1063, N'4452', N'Fabric Coating or Impregnating NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1074, N'4459', N'Adhesives Mfg.—Plastic—Sheets and Liquid')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1085, N'4470', N'Cable Mfg.—Insulated Electrical')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1087, N'4484', N'Automobile, Bus, Truck, or Trailer Body Mfg.—Fiberglass')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1098, N'4493', N'Fabric Coating or Impregnating NOC.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1102, N'4511', N'Analytical Chemist')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1118, N'4519', N'Exterminator & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1122, N'4557', N'Buffing or Polishing Compounds Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1133, N'4558', N'Candle Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1148, N'4568', N'Borax, Potash or Salt Producing or Refining & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1151, N'4581', N'Phosphate Works & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1152, N'4583', N'Compost Mfg.—Cotton Hulls & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1155, N'4611', N'Aloe Vera Plant Processing & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1167, N'4635', N'Freon Recycling by Specialty Contractor & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1170, N'4653', N'Glue Mfg. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1171, N'4665', N'Rendering Works NOC & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1172, N'4670', N'Cottonseed Oil Mfg. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1176, N'4683', N'Cottonseed Oil Refining')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1179, N'4686', N'Oil Mfg.—Vegetable—Solvent Extraction Process')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1180, N'4692', N'Dental Laboratory')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1181, N'4693', N'Instrument Sterilizing—Medical')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1184, N'4703', N'Dextrin Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1185, N'4712', N'Asphalt or Tar Distilling or Refining & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1192, N'4716', N'Grease Processing Plant—For Restaurant Grease Exclusively')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1194, N'4717', N'Butter Substitute Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1195, N'4720', N'Detergent Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1197, N'4740', N'Gasohol Mfg. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1203, N'4741', N'Asphalt or Tar Distilling or Refining & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1204, N'4743', N'Gasoline Recovery & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1205, N'4751', N'Carbon Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1208, N'4766', N'Dynamite Mfg. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1214, N'4771', N'Explosives or Ammunition Mfg. NOC & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1215, N'4777', N'Blasting Agents—Preparation or Distribution & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1217, N'4805', N'Insecticide Mfg.—Liquid—For Household Use')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1218, N'4807', N'Fertilizer Mfg.—Liquid for Home Type Plants')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1220, N'4811', N'Agriculture Chemicals Mfg.—Highly Poisonous')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1224, N'4814', N'Plastic Mixing—Liquid Material for Waterproofing')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1227, N'4815', N'Acid Mfg. NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1239, N'4819', N'Aerosol Canning—Pressurized')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1242, N'4823', N'Bacteria Production for Sewage Disposal Plants')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1247, N'4825', N'Drug, Medicine or Pharmaceutical Preparation Mfg.—Includes Mfg. of Ingredients')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1253, N'4828', N'Chemical Blending or Mixing NOC—All Operations & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1254, N'4829', N'Acid Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1260, N'4902', N'Archery Supplies Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1266, N'4923', N'Computer Floppy Disk & Magnetic Tape Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1269, N'5020', N'Ceiling Installation—Suspended Acoustical Grid Type.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1270, N'5022', N'Caulking Exterior of Buildings & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1282, N'5037', N'Painting')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1283, N'5040', N'Concrete Construction—Erection of Precast and Prestressed Structural Concrete Products or Tilt-Up Wall Sections—Buildings Over Two Stories in Height')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1286, N'5041', N'Painting—Steel Structures or Bridges')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1288, N'5057', N'Building Crane Erection at Construction Site & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1298, N'5059', N'Iron or Steel—Erection—Frame Structures Not Over Two Stories in Height.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1299, N'5069', N'Iron or Steel—Erection—Construction of Dwellings Not Over Two Stories in Height')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1300, N'5070', N'Burglar Guards or Bars—Installation')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1302, N'5102', N'Aluminum Door, Window and Frame Installation & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1327, N'5146', N'Fixtures or Furniture Installation—Portable—NOC.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1331, N'5160', N'Elevator—Erection or Repair')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1332, N'5183', N'Air Conditioning Systems—Heating and/or Cooling—Not Portable—Installation and Service of Packaged or Central Units Including Plumbing & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1353, N'5188', N'Automatic Sprinkler Installation & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1355, N'5190', N'Air Conditioning Systems—Heating and/or Cooling—Portable Units—Installation and Service Window Units & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1366, N'5191', N'Automatic Door Control Installation')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1379, N'5192', N'Ice Machines—Sales, Rental, Installation, and Service & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1382, N'5200', N'Cable Tension System Installation—For Concrete Slabs & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1392, N'5203', N'Concrete Construction—Bridges & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1394, N'5213', N'Building Cleaning—Exterior—Chemical Process & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1412, N'5215', N'Concrete Construction—Private Residences—Not Monolithic')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1414, N'5220', N'Artificial Turf Installation & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1420, N'5221', N'Concrete or Cement Work—Floors, Driveways, Yards, or Sidewalks & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1424, N'5222', N'Chimney Construction—Not Metal.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1427, N'5223', N'Swimming Pool—Construction—Not Iron or Steel & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1428, N'5348', N'Ceramic Tile Installation—Inside')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1437, N'5402', N'Greenhouse Erection—All Operations')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1439, N'5403', N'Aluminum Awning Erection & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1449, N'5437', N'Carpentry—Installation of Cabinet Work or Interior Trim & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1460, N'5443', N'Lathing & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1461, N'5445', N'Wallboard, Sheetrock, Drywall, Plasterboard, or Cement Board Installation—Within Buildings & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1462, N'5462', N'Glazier—Away From Shop & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1463, N'5472', N'Asbestos Removal Operations—Contractor—Pipe and Boiler Work Exclusively & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1464, N'5473', N'Asbestos Removal Operations—Contractor—NOC & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1465, N'5474', N'Caulking Interior of Buildings & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1474, N'5478', N'Floor Covering Installation—Resilient Flooring—Carpet and Laminate Flooring')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1475, N'5479', N'Acoustical Material Installation & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1480, N'5480', N'Plastering NOC & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1481, N'5491', N'Automobile Glass Tinting—No Other Operations & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1486, N'5506', N'Airport Runway Construction & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1495, N'5507', N'Street or Road Construction—Subsurface Work & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1496, N'5508', N'Street or Road Construction—Rock Excavation & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1497, N'5535', N'Awning Erection—Metal—Erection of Metal Awnings Exclusively & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1501, N'5536', N'Air Conditioning Systems—Heating and/or Cooling—Not Portable—Duct Fabrication or Installation & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1502, N'5537', N'Heating, Ventilation, Air-Conditioning and Refrigeration Systems—Installation, Service and Repair, Shop, Yard Work & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1503, N'5538', N'Aluminum Paneling or Sheet Metal Facing Installation—Building Exteriors & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1513, N'5551', N'Roofing—All Kinds & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1514, N'5606', N'Contractor—Executive Supervisor or Construction Superintendent')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1515, N'5610', N'Cleaner—Debris Removal—Construction')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1518, N'5645', N'Carpentry—Construction of Residential Dwellings Not Exceeding Three Stories in Height')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1520, N'5701', N'Salvage Operation—No Wrecking or Structural Operations & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1521, N'5703', N'Building Raising or Moving')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1522, N'5951', N'Antitoxin, Serum, or Virus Mfg. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1525, N'6003', N'Pile Driving & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1526, N'6005', N'Jetty or Breakwater Construction—All Operations to Completion & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1527, N'6017', N'Dam or Lock Construction—Concrete Work—All Operations')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1528, N'6018', N'Dam or Lock Construction—Earth Moving or Placing—All Operations & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1529, N'6045', N'Breakwater or Jetty Construction—All Operations to Completion & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1538, N'6202', N'Derrick or Oil Rig Erecting or Dismantling—All Operations & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1551, N'6203', N'Oil or Gas Well—Drilling—Executive Supervisor')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1553, N'6204', N'Boring Under Streets & Railroads & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1561, N'6205', N'Sulphur Producing—All Employees & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1563, N'6206', N'Nitrogen Injection Into Oil Wells & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1568, N'6213', N'Blowout Preventer Testing and Tightening in Field & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1582, N'6214', N'Oil or Gas—Well—Perforating of Casing—All Employees & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1583, N'6216', N'Drill Site Preparation—Oil or Gas Wells & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1591, N'6217', N'Airport Construction—Grading & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1597, N'6219', N'Agriculture Land Clearing & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1640, N'6229', N'Irrigation Pipe Installation—Underground—Not Lawn Sprinklers & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1642, N'6233', N'Oil or Gas Pipeline Construction & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1647, N'6235', N'Drilling or Redrilling of Oil or Gas Wells & Installation of Casing, Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1650, N'6236', N'Oil or Gas—Well—Installation or Recovery of Casing & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1651, N'6237', N'Drilling Mud Engineers & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1654, N'6238', N'Casing Installation—Oil Well & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1659, N'6251', N'Tunneling—Not Pneumatic—All Operations')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1660, N'6252', N'Caisson Work—All Operations to Completion.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1663, N'6260', N'Tunneling—Pneumatic—All Operations')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1664, N'6306', N'Caisson Work—All Operations to Completion & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1669, N'6319', N'Aqueduct Construction & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1674, N'6325', N'Conduit Construction—For Cables or Wires & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1675, N'6400', N'Chain Link Fence Construction')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1679, N'6503', N'Potato Chip, Popcorn & Snack Chip Mfg. NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1680, N'6504', N'Baking Powder Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1698, N'6702', N'Railroad Construction—All Operations Including Clerical, Salespersons & Drivers—Coverage Under the Federal Employers’ Liability Act (FELA)—Program I')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1699, N'6703', N'Railroad Construction—All Operations Including Clerical, Salespersons & Drivers—Coverage Under the Federal Employers’ Liability Act (FELA)—Program II—USL&HW Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1700, N'6704', N'Railroad Construction—All Operations Including Clerical, Salespersons & Drivers—Coverage Under the Federal Employers’ Liability Act (FELA)—Program II—State Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1701, N'6801F', N'Boatbuilding—Wood NOC & Drivers—Coverage Under U.S. Act')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1702, N'6811', N'Boatbuilding—Wood NOC & Drivers—Coverage Under State Act Only')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1703, N'6823', N'Aluminum Boat Mfg.—Pleasure Craft')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1706, N'6824F', N'Boat Building or Repair NOC & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1707, N'6826F', N'Marina & Drivers—Coverage Under U.S. Act')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1708, N'6836', N'Marina & Drivers—Coverage Under State Act Only')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1709, N'6843F', N'Ship Building—Iron or Steel—NOC & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1710, N'6845F', N'Shipbuilding—Naval & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1711, N'6872F', N'Barge Cleaning & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1714, N'6874F', N'Ship Scaling')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1715, N'6882', N'Marine Railway Operation & Drivers—Coverage Under State Act Only')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1716, N'6884', N'Painting—Ship Hulls—Coverage Under State Act Only')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1717, N'7016', N'Ferries—Coverage Under Admiralty Law—Program I')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1723, N'7024', N'Ferries—Coverage Under Admiralty Law—Program II—State Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1729, N'7038', N'Vessels—Sail—Coverage Under Admiralty Law—Program I')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1731, N'7046', N'Vessels—Not Self-Propelled—Coverage Under Admiralty Law—Program I')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1732, N'7047', N'Ferries—Coverage Under Admiralty Law—Program II—USL&HW Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1738, N'7050', N'Vessels—Sail—Coverage Under Admiralty Law—Program II—USL&HW Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1740, N'7090', N'Vessels—Sail—Coverage Under Admiralty Law—Program II—State Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1742, N'7098', N'Vessels—Not Self-Propelled—Coverage Under Admiralty Law—Program II—State Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1743, N'7099', N'Vessels—Not Self-Propelled—Coverage Under Admiralty Law—Program II—USL&HW Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1744, N'7133', N'Railroad Construction—Railroad Operation and Maintenance—Coverage Under the Federal Employers’ Liability Act (FELA)—Program I')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1745, N'7134', N'Railroad Construction—Railroad Operation and Maintenance—Coverage Under the Federal Employers’ Liability Act (FELA)—Program II State Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1746, N'7135', N'Railroad Construction—Railroad Operation and Maintenance—Coverage Under the Federal Employers’ Liability Act (FELA)—Program II USL Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1747, N'7151', N'Railroad Operation—All Employees Including Drivers—Coverage Under the Federal Employers’ Liability Act (FELA)—Program I')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1748, N'7152', N'Railroad Operation—All Employees Including Drivers—Coverage Under the Federal Employers’ Liability Act (FELA)—Program II—USL&HW Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1749, N'7153', N'Railroad Operation—All Employees Including Drivers—Coverage Under the Federal Employers’ Liability Act (FELA)—Program II—State Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1750, N'7219', N'Automobile Towing Companies—No Other Operations & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1767, N'7228', N'Automobile')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1769, N'7229', N'Automobile')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1771, N'7230', N'Advertising Circular Distribution—By Contract & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1780, N'7231', N'Mail, Parcel, or Package Delivery and Courier or Messenger Service Companies —All Employees & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1781, N'7309F', N'Stevedoring—NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1782, N'7313F', N'Ore Dock Operation and Stevedoring')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1784, N'7317F', N'Barge Loading by Contract—No Use of Hoisting Equipment')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1792, N'7327F', N'Stevedoring—Containerized Freight & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1793, N'7333', N'Dredging—All Types—Coverage Under Admiralty Law—Program I')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1794, N'7335', N'Dredging—All Types—Coverage Under Admiralty Law—Program II—State Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1795, N'7337', N'Dredging—All Types—Coverage Under Admiralty Law—Program II—USL&HW Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1796, N'7350', N'Freight Handler NOC—Coverage Under US Act')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1797, N'7360', N'Freight Handler NOC—Coverage Under State Act Only')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1801, N'7370', N'Limousine Co.—All Other Employees & Drivers—Nonscheduled')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1803, N'7380', N'Chauffeurs, Drivers, and Their Helpers NOC—Commercial')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1806, N'7382', N'Horse & Carriage Tours & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1809, N'7390', N'Ale or Beer Dealer—Wholesale & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1811, N'7394', N'Diving—Marine—Coverage Under Admiralty Law—Program I')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1813, N'7395', N'Diving—Marine—Coverage Under Admiralty Law—Program II—State Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1815, N'7398', N'Diving—Marine—Coverage Under Admiralty Law—Program II—USL&HW Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1817, N'7402', N'Aviation—Air Traffic Controllers Under Contract With the FAA')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1818, N'7403', N'Aviation—Airport or Heliport Operator—All Employees & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1822, N'7405', N'Aircraft or Helicopter Operation—Air Carrier—Scheduled or Supplemental—Flying Crew')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1823, N'7418', N'Air Traffic Reporters')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1835, N'7420', N'Aviation—Aerial Application, Seeding, Herding, or Scintillometer Surveying—Flying Crew')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1838, N'7421', N'Aircraft or Helicopter Operation—Transportation of Personnel in Conduct of Employer’s Business—Flying Crew')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1839, N'7422', N'Aircraft or Helicopter Operation NOC—Flying Crew')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1844, N'7423', N'Aircraft Ground Support Equipment Repair & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1865, N'7425', N'Aviation—Helicopters—Flying Crew')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1866, N'7431', N'Aviation—Air Charter or Air Taxi—Flying Crew')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1867, N'7502', N'Gas Co.—Natural Gas—Local Distribution & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1869, N'7515', N'Gas Meter—Natural—Calibration & Service & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1873, N'7520', N'Flood Control District & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1877, N'7538', N'Electric Light or Power Line Construction & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1879, N'7539', N'Electric Light or Power Co. NOC—All Employees & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1880, N'7540', N'Electric Light or Power Cooperative—REA Project Only—All Employees & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1881, N'7580', N'Sewage Disposal Plant Operation & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1882, N'7590', N'Environmental Cleanup—Soil Incineration at Permanent Facility')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1885, N'7600', N'Burglar Alarm Installation or Repair & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1904, N'7602', N'Fire Alarm, Telephone, or Telegraph Line Construction & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1909, N'7605', N'Burglar and Fire Alarm Installation or Repair & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1910, N'7610', N'Radio or Television Broadcasting Station—All Employees & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1915, N'7704', N'Firefighters & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1917, N'7705', N'Ambulance Service Companies and EMS (Emergency Medical Service) Providers & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1918, N'7710', N'Fire Patrol or Protective Corps & Drivers—No Salvage Operations')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1921, N'7711', N'Fire Patrol or Protective Corps & Drivers—Volunteer')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1924, N'7720', N'Ambulance Service by Contract & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1934, N'7855', N'Railroad Construction—Laying or Re-Laying of Tracks or Maintenance of Way by Contractor—No Work on Elevated Railroads & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1936, N'8001', N'Florist.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1938, N'8002', N'Automobile—Rental Co.—All Other Employees & Counter Personnel, Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1940, N'8006', N'Convenience Store')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1948, N'8008', N'Clothing or Wearing Apparel Store—Retail')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1953, N'8010', N'Bicycles—Retail Sale or Rental')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1959, N'8013', N'Diamond Cutting or Polishing')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1965, N'8015', N'Quick Printing—Copying or Duplicating Service—All Employees & Clerical, Salespersons, Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (1966, N'8017', N'Aircraft Parts Dealer—Retail & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2126, N'8018', N'Aircraft Parts Dealer—Wholesale & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2259, N'8021', N'Store—Fish, Meat or Poultry Dealer—Wholesale.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2261, N'8031', N'Cold Storage Locker—Frozen Foods.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2264, N'8032', N'Clothing or Wearing Apparel Store—Wholesale')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2267, N'8033', N'Cold Storage Locker—Frozen Foods')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2277, N'8034', N'Egg Dealer—Including Grading, Candling, Packing—Wholesale')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2292, N'8037', N'Store—Superstores and Warehouse Clubs')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2293, N'8039', N'Department Store—Retail')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2295, N'8044', N'Furniture Store—All Other Employees & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2297, N'8045', N'Drug Store—Retail & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2301, N'8046', N'Automobile')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2303, N'8047', N'Drug Store—Wholesale')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2304, N'8058', N'Building Material Dealer—Store Employees')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2308, N'8072', N'Store—Audio or Video Cassette, Book, Record, Compact Disc, Software—Retail.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2314, N'8102', N'Cottonseed Delinting—All Methods')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2318, N'8103', N'Clippings Dealer.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2323, N'8105', N'Store—Hide or Leather Dealer')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2325, N'8106', N'Cement Lining of Tubular Goods—Not Oil Field & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2327, N'8107', N'Brass or Copper Dealer—Wholesale & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2365, N'8111', N'Plumbers’ Supplies Dealer & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2366, N'8113', N'Oil or Gas Pipe Coating and Wrapping—Shop or Yard & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2370, N'8116', N'Farm Machinery Dealer—All Operations & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2371, N'8203', N'Ice Mfg. or Distribution & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2372, N'8204', N'Building Material—Yard & Local Managers, Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2374, N'8209', N'Vegetable Packing & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2375, N'8215', N'Feed Supplement Blending & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2383, N'8227', N'Contractor’s Permanent Yard')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2384, N'8231', N'Cedar Chip Grinding and Sacking & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2390, N'8232', N'Building Material Dealer—New Materials Only—All Other Employees & Yard, Warehouse, Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2395, N'8233', N'Coal Merchant & Local Managers, Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2396, N'8234', N'Building Material Dealer—All Other Employees & Yard, Warehouse, Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2420, N'8235', N'Sash, Door, or Assembled Millwork—Dealer & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2421, N'8263', N'JUNK DEALER & DRIVERS')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2422, N'8264', N'Aluminum Can Recycling or Shredding & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2434, N'8265', N'Automobile Crushing or Shredding & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2441, N'8279', N'Breeding Farm or Stable & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2449, N'8288', N'Cattle Dealer & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2457, N'8291', N'Storage Warehouse—Cold')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2459, N'8292', N'Freight Forwarding Warehouse & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2466, N'8293', N'Household Goods—Packing & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2469, N'8295', N'Cotton Compressing & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2472, N'8304', N'Rice Drying & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2473, N'8350', N'Aircraft Fueling—Ground Operations by Contract & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2486, N'8380', N'Air Conditioning Systems—Automobile—Installation, Service or Repair & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2493, N'8381', N'Gasoline Station—Self-Service Only—Retail')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2494, N'8385', N'Automobile Rental Co.—Garage Employees')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2495, N'8387', N'Automobile Lubrication, Greasing, and Maintenance & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2501, N'8391', N'Aircraft Painting & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2537, N'8392', N'Automobile Storage Garage, Parking Lot or Parking Station, Valet Service, Cashiers or Counter Personnel & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2538, N'8393', N'Automobile—Body Repair')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2539, N'8500', N'METAL SCRAP DEALER & DRIVERS')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2540, N'8601', N'Air Flow Balancing of Air Conditioning Systems')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2550, N'8602', N'Surveyors, Timber Cruisers, Oil or Gas Geologists or Scouts, & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2551, N'8603', N'Architectural or Engineering Firm—Clerical')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2553, N'8606', N'Geophysical Exploration—All Employees & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2555, N'8607', N'Ecology Studies—Water, Fish, Animals, Etc. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2557, N'8709F', N'Steamship Line or Agency—Port Employees—Talliers, Checking Clerks and Employees Engaged in Mending or Repacking of Damaged Containers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2560, N'8719', N'Steamship Line or Agency—Port Employees—Talliers, Checking Clerks, and Employees Engaged in Mending or Repacking of Damaged Containers—Coverage Under State Act Only')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2561, N'8720', N'Inspection of Risks for Insurance or Valuation Purposes NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2563, N'8721', N'Real Estate Agency—Outside Employees & Collectors')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2565, N'8723', N'Insurance Companies—Including Clerical & Salespersons')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2566, N'8725', N'Inventory Counters—Traveling—Including Salespersons & Clerical')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2567, N'8726F', N'Steamship Line or Agency—Port Employees—Superintendents, Captains, Engineers, Stewards or Their Assistants, Pay Clerks')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2569, N'8734', N'Salespersons or Collectors—Outside—Program II—State Act Benefits—Coverage Under the Federal Employers’ Liability Act (FELA)')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2570, N'8737', N'Salespersons or Collectors—Outside—Program I—Coverage Under the Federal Employers’ Liability Act (FELA)')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2571, N'8738', N'Salespersons or Collectors—Outside—Program II—USL&HW Act Benefits—Coverage Under the Federal Employers’ Liability Act (FELA)')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2572, N'8742', N'Appraisers—Tax')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2589, N'8748', N'Automobile Salespersons')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2593, N'8752', N'Coffee Maker Rental & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2600, N'8754', N'Furniture Store—Inside Sales Employees')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2602, N'8755', N'Labor Union—All Employees.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2603, N'8799', N'Mailing or Addressing Company or Letter Service Shop—Clerical Staff')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2604, N'8800', N'Mailing or Addressing Company or Letter Service Shop')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2605, N'8803', N'Accountant, Auditor, or Factory Cost or Office Systematizer—Traveling')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2611, N'8805', N'Clerical Office Employees NOC—Coverage Under the Federal Employers’ Liability Act (FELA)—Program II—State Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2612, N'8809', N'Executive Officers NOC—Performing Clerical or Outside Salespersons Duties Only')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2613, N'8810', N'Air Traffic Controllers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2625, N'8814', N'Clerical Office Employees NOC—Coverage Under the Federal Employers’ Liability Act (FELA)—Program I')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2626, N'8815', N'Clerical Office Employees NOC—Coverage Under the Federal Employers’ Liability Act (FELA)—Program II—USL&HW Act Benefits')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2627, N'8820', N'Abstract or Title Co.—All Employees & Clerical, Messengers, Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2630, N'8824', N'Retirement Living Centers—Health Care Employees')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2631, N'8825', N'Retirement Living Centers—Food Service Employees')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2632, N'8826', N'Retirement Living Centers—All Other Employees & Salespersons, Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2633, N'8828', N'Home Healthcare—All Other Employees')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2636, N'8829', N'Convalescent or Nursing Home—All Employees')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2640, N'8831', N'Alligator Control—Removal of Nuisance Alligators & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2651, N'8832', N'Blood Banks')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2664, N'8833', N'Ambulance Service—Air Ambulance—Medical Personnel')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2673, N'8835', N'Home, Public, and Traveling Healthcare—All Employees')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2675, N'8837', N'Charitable or Religious Organization—Welfare—All Operations & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2678, N'8838', N'Library—Public—Professional Employees')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2682, N'8842', N'Group Homes—All Employees & Salespersons, Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2683, N'8855', N'Banks and Trust Companies—All Employees, Salespersons, Drivers & Clerical')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2684, N'8856', N'Check Cashing Establishments—All Employees, Salespersons, Drivers & Clerical')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2685, N'8858', N'Aircraft Ground School')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2686, N'8864', N'Social Services Organization—All Employees & Salespersons, Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2687, N'8868', N'Children’s Home—Professional Employees')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2704, N'8869', N'Child Care Center—All Employees Including Clerical, Salespersons & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2707, N'8901', N'Alarm Monitoring & Clerical')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2712, N'9012', N'Building or Property Management—Property Managers and Leasing Agents & Clerical, Salespersons')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2716, N'9014', N'Air Conditioning Duct Cleaning Service')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2746, N'9015', N'Automobile Auctions & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2778, N'9016', N'Amusement Device Operation NOC—Not Traveling & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2802, N'9019', N'Bridge or Vehicular Tunnel Operation & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2804, N'9032', N'Apartment House Operation')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2805, N'9033', N'Housing Authority & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2806, N'9040', N'Hospices—All Other Employees')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2807, N'9044', N'Casino Gambling—Hotel—All Employees & Clerical, Salespersons, Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2808, N'9052', N'Boarding Houses or Rooming Houses & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2814, N'9058', N'Retirement Centers or Villages—Ambulatory Residents—Restaurant Employees')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2815, N'9060', N'Club—Country, Golf, Fishing, or Yacht')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2818, N'9061', N'Club—NOC')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2820, N'9062', N'Casino Gambling—All Employees & Clerical, Salespersons, Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2821, N'9063', N'Aerobic Studios & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2828, N'9077F', N'United States Armed Service Risk—All Employees & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2829, N'9079', N'Bar, Night Club, or Tavern')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2845, N'9080', N'Dance Hall—All Operations')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2846, N'9082', N'Caterer.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2848, N'9083', N'Doughnut Shop—Retail.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2850, N'9084', N'Bar, Discotheque, Lounge, Nightclub or Tavern.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2851, N'9088', N'Rocket or Missile Testing or Launching & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2852, N'9089', N'Billiard Hall')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2853, N'9093', N'Bowling Lane & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2855, N'9101', N'Children’s Home—All Other Employees & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2875, N'9102', N'Park NOC—All Employees & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2876, N'9154', N'Bands—Traveling—All Other Employees')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2880, N'9156', N'Bands—Traveling—Players, Entertainers or Musicians')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2882, N'9170', N'Cleaning Buildings, Statues, Metal Awnings—Multistory & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2884, N'9178', N'Athletic Team—Noncontact Sports')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2885, N'9179', N'Athletic Team—Contact Sports')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2886, N'9180', N'Amusement Device Operation NOC Not Traveling & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2890, N'9182', N'Athletic Park Operation & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2891, N'9186', N'Amusement Device Operator, Carnival, or Circus—Traveling—All Employees & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2894, N'9220', N'Cemetery Operation & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2895, N'9402', N'Ashes, Garbage, or Refuse Collection & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2913, N'9403', N'Ashes, Garbage, or Refuse Collection & Drivers.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2916, N'9410', N'Municipal, Township, County, or State Employee NOC.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2917, N'9501', N'Booth or Display Mfr. for Trade Shows, Conventions & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2923, N'9505', N'Automobile, Bus, Truck or Trailer Body Mfg.—Painting')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2925, N'9516', N'Electronic Equipment—Installation, Service, or Repair—Shop and Outside & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2926, N'9519', N'Air Conditioning Systems—Portable Units—Installation, Service or Repair & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2928, N'9521', N'Advertising Display Installation Service')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2932, N'9522', N'Coffin or Casket Upholstering and Burial Garment Mfg.')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2934, N'9529', N'Concrete or Cement Distributing Towers—Installation, Repair, or Removal & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2939, N'9534', N'Bell Installation—Tower & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2941, N'9552', N'Advertising Co. & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2949, N'9554', N'Sign Installation, Maintenance, Repair, Removal, or Replacement NOC—Away From Shop & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2951, N'9586', N'Barber Shop')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2956, N'9600', N'Taxidermist')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2957, N'9620', N'Crematory Operation & Drivers')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2960, N'9984', N'Atomic Energy—Project Work')
INSERT INTO [dbo].[Codes] ([Id], [Number], [JobDescription]) VALUES (2961, N'9985', N'Atomic Energy—Radiation Exposure NOC')
SET IDENTITY_INSERT [dbo].[Codes] OFF
